import 'package:new_mama/feature/community/data/models/comment_model.dart';

final dummyComments = [
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=1',
    name: 'Sarah Johnson',
    timeAgo: '2h ago',
    comment: 'This is so helpful! Thank you for sharing your experience 💕',
    likes: 24,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=2',
        name: 'Jessica Lee',
        timeAgo: '1h ago',
        comment: 'I totally agree! This helped me so much.',
        likes: 5,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=3',
        name: 'Ana Soso',
        timeAgo: '45m ago',
        comment: 'Thank you both! Glad I could help 🌸',
        likes: 8,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=4',
        name: 'Maria Garcia',
        timeAgo: '30m ago',
        comment: 'Same here! You\'re amazing!',
        likes: 3,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=5',
    name: 'Emma Williams',
    timeAgo: '5h ago',
    comment:
        'I went through the same thing! It gets easier, I promise. Stay strong mama! 💪',
    likes: 18,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=6',
        name: 'Lisa Brown',
        timeAgo: '3h ago',
        comment: 'Thank you for the encouragement! ❤️',
        likes: 4,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=9',
    name: 'Olivia Brown',
    timeAgo: '8h ago',
    comment: 'Great advice! I wish I had known this earlier.',
    likes: 12,
    isLiked: false,
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=12',
    name: 'Sophia Davis',
    timeAgo: '12h ago',
    comment: 'Can you share more details about this? I\'m really interested!',
    likes: 8,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=13',
        name: 'Ana Soso',
        timeAgo: '10h ago',
        comment: 'Of course! I\'ll post more details soon.',
        likes: 6,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=14',
        name: 'Rachel Green',
        timeAgo: '9h ago',
        comment: 'Looking forward to it!',
        likes: 2,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=16',
    name: 'Ava Martinez',
    timeAgo: '1d ago',
    comment: 'You\'re doing amazing! Keep it up! 🌟',
    likes: 31,
    isLiked: false,
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=20',
    name: 'Isabella Garcia',
    timeAgo: '1d ago',
    comment: 'This made my day! Thank you for posting this ❤️',
    likes: 15,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=21',
        name: 'Ana Soso',
        timeAgo: '20h ago',
        comment: 'So glad to hear that! 💕',
        likes: 7,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=23',
    name: 'Mia Rodriguez',
    timeAgo: '2d ago',
    comment:
        'I have a question - how did you manage to do this while taking care of the baby?',
    likes: 6,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=24',
        name: 'Ana Soso',
        timeAgo: '1d ago',
        comment: 'It wasn\'t easy! I did it during nap times mostly.',
        likes: 9,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=25',
        name: 'Sophie Turner',
        timeAgo: '1d ago',
        comment: 'That\'s dedication! 👏',
        likes: 4,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=26',
        name: 'Emily Davis',
        timeAgo: '20h ago',
        comment: 'You inspire me!',
        likes: 3,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=28',
        name: 'Hannah White',
        timeAgo: '18h ago',
        comment: 'Same question here! Thanks for sharing.',
        likes: 2,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=27',
    name: 'Charlotte Wilson',
    timeAgo: '2d ago',
    comment: 'Absolutely love this! Saving for later 📌',
    likes: 9,
    isLiked: false,
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=30',
    name: 'Amelia Anderson',
    timeAgo: '3d ago',
    comment: 'This is exactly what I needed to hear today. Thank you! 🙏',
    likes: 22,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=31',
        name: 'Grace Miller',
        timeAgo: '2d ago',
        comment: 'Me too! Perfect timing.',
        likes: 5,
        isLiked: false,
      ),
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=32',
        name: 'Ana Soso',
        timeAgo: '2d ago',
        comment: 'Happy to help! 💗',
        likes: 6,
        isLiked: false,
      ),
    ],
  ),
  CommentModel(
    profileUrl: 'https://i.pravatar.cc/150?img=33',
    name: 'Harper Thomas',
    timeAgo: '3d ago',
    comment: 'So relatable! We\'re all in this together 💗',
    likes: 14,
    isLiked: false,
    repliesList: [
      CommentModel(
        profileUrl: 'https://i.pravatar.cc/150?img=34',
        name: 'Victoria King',
        timeAgo: '2d ago',
        comment: 'Absolutely! Mom community is the best 🤗',
        likes: 8,
        isLiked: false,
      ),
    ],
  ),
];
