// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQboDJAxuOgQP8KFcHyTPhqwSTZV9Mgg',
    appId: '1:517446421949:web:c54f5f71c6fa25797256d4',
    messagingSenderId: '517446421949',
    projectId: 'momease-b0a1e',
    authDomain: 'momease-b0a1e.firebaseapp.com',
    storageBucket: 'momease-b0a1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_s6epScjJayoI8RvjLmonp-yaWpHdYU',
    appId: '1:517446421949:android:d39b1d2db46f02dd7256d4',
    messagingSenderId: '517446421949',
    projectId: 'momease-b0a1e',
    storageBucket: 'momease-b0a1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANot7zAbSYFeBdUqQKVOHo7ppZRFHqBuI',
    appId: '1:517446421949:ios:b53eadc93892c0b77256d4',
    messagingSenderId: '517446421949',
    projectId: 'momease-b0a1e',
    storageBucket: 'momease-b0a1e.firebasestorage.app',
    iosBundleId: 'com.postcare.app',
  );
}
